import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'

export default function CalculatorPage() {
  return (
      <div className={styles.container}>
        <Head>
          <title>Calculator</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to Calculator!!!
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
          </p>
        </main>
      </div>
  )
}
